iBuy/iBuy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('istore.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

iBuy/istore/urls.py
from django.urls import path
from . import views


app_name='istore'


urlpatterns=[
  path('',views.homepage,name="homepage"),
  path('istore/cart/summary',views.cart_view,name="summary"),
  path('istore/cart/checkout/',views.checkout_view,name="checkout"),
  path('istore/cart/<slug:slug>',views.add_to_cart,name="cart"),
  path('istore/cart_add/<slug:slug>',views.add_one_cart,name="one_cart"),
  path('istore/cart/remove_cart/<slug:slug>',views.remove_cart,name='remove_cart'),
  path('istore/cart/remove_one_cart/<slug:slug>',views.remove_one_cart,name="remove_one_cart"),
  path('istore/product/description/<slug:slug>',views.desc_view,name="description"),
  path('istore/cart/verify_payment/<str:ref>', views.verify_payment, name="verify_payment"),
  
  
  ]

iBuy/istore/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models import Sum
from django.dispatch import receiver
from django.shortcuts import reverse
from .paystack import PayStack
# Create your models here.
#class Customer(models.Model):
  #User=models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)
  #name=models.CharField(max_length=200,null=True)
  #Email=models.EmailField(max_length=200)
  
  #def __str__(self):
   # return self.name
   

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)


    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Categories(models.Model):
  category=models.CharField(max_length=500,null=False)
  date_added=models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return self.category




class Product(models.Model):
  name=models.CharField(max_length=200,null=True)
  slug=models.SlugField()
  category=models.ForeignKey(Categories,on_delete=models.SET_NULL,blank=True,null=True)
  price=models.FloatField()
  digital=models.BooleanField(default=False,null=True,blank=False)
  thumb=models.ImageField(default='default.png',null=True)
  description=models.TextField(null=True)
  def __str__(self):
    return self.name
    
  #def get_absolute_url(self):
    #return reverse("istore:cart",kwargs={'slug':self.slug})


  
class ShippingAddress(models.Model):
  customer=models.ForeignKey(Profile,on_delete=models.SET_NULL,blank=True,null=True)
  address=models.CharField(max_length=250)
  city=models.CharField(max_length=250)
  phone_number=models.IntegerField(null=True)
  zip = models.CharField(null=True, max_length=200)
  country = models.CharField(null=True, max_length=200)
  
  def __str__(self):
    return self.address

    
    

class OrderItem(models.Model):
  customer=models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
  product=models.ForeignKey(Product,on_delete=models.SET_NULL,null=True)
  quantity=models.IntegerField(default=1,null=True,blank=True)
  complete=models.BooleanField(default=False,null=True,blank=False)
  date_added=models.DateTimeField(auto_now_add=True)

  
  def __str__(self):
    return f"{self.quantity} of {self.product.name}"
  @property
  def get_item_price(self):
    total =self.product.price * self.quantity
    return total





class Order(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
  customer=models.ForeignKey(Profile,on_delete=models.SET_NULL,blank=True,null=True)
  products=models.ManyToManyField(OrderItem)
  address=models.ForeignKey(ShippingAddress,on_delete=models.SET_NULL,null=True)
  date_order=models.DateTimeField(auto_now_add=True)
  amount=models.CharField(null=True,max_length=200)
  complete=models.BooleanField(default=False,null=True,blank=True)
  transaction_id=models.CharField(max_length=100)
  def __str__(self):
    return f'{self.customer}'
  @property
  def get_cart_total(self):
    orderitem=self.products.all()
    total=sum([item.get_item_price for item in orderitem])
    return total
    
  def verify_payment(self):
    paystack = PayStack()
    order_item = OrderItem.objects.filter(customer =self.customer , complete = False)
    status, result = paystack.verify_payment(self.transaction_id , self.get_cart_total)
    if status:
      if result['amount'] / 100 == self.get_cart_total:
        self.complete = True
        self.amount = self.get_cart_total
        self.products.complete = True
        for order_item in order_item:
            order_item.complete = True
            order_item.save()
        self.save()
     

      if self.complete:
          return True
    return False
    
    
class Payment(models.Model):
  customer=models.ForeignKey(Profile,on_delete=models.SET_NULL,blank=True,null=True)
  amount=models.IntegerField(null=True,blank=True)
  date_paid=models.DateTimeField(auto_now_add=True)
  reference=models.CharField(max_length=100)
  
  
  def __str__(self):
    return f'{self.customer}'

  
  

  
  
  
  

iBuy/istore/forms.py
from django import forms
from .models import *




class ShipAddress(forms.ModelForm):
  
  
  address=forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}),required=True)
  
  
  city=forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}),required=True)
  
  
  phone_number=forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class':'form-control'}),required=True)
  class Meta:
    model=ShippingAddress
    
    fields=[
      
      'address','city','phone_number'
      
      ]

iBuy/istore/views.py
from django.shortcuts import render,redirect
from  .models import *
from django.shortcuts import get_object_or_404
from random import randint
from django.contrib import messages
from django.contrib.auth.decorators  import login_required
from django.core.exceptions import ObjectDoesNotExist
from .forms import ShipAddress
from django.http.request import HttpRequest
from django.http.response import HttpResponse


# Create your views here.

def homepage(request):
 
  product=Product.objects.all()
  try:
    user=request.user
    customer=request.user.profile
    order=Order.objects.get(customer=customer,user=user,complete=False)
    context={
      'product':product,
      'order':order
    }
  except:
    context={
      'product':product,
    }
    return render(request,'istore/index.html', context)

  return render(request,'istore/index.html',context)


def desc_view(request,slug):
  product=Product.objects.get(slug=slug)
  context = {
    'product':product
    }
  return render(request,'istore/product-single.html',context)

@login_required
def add_to_cart(request,slug):
  if request.user.is_authenticated:
    user=request.user
    customer=request.user.profile
    product=get_object_or_404(Product, slug=slug)
    order_item, created=OrderItem.objects.get_or_create(customer=customer,product=product,complete=False)
    order_qs=Order.objects.filter(customer=customer,user=user,complete=False)
    if order_qs.exists():
      order=order_qs[0]
      if order.products.filter(product__slug=product.slug).exists():
        
        order_item.quantity += 1
        order_item.save()
        messages.info(request,"Quantity successfully updated")
        return redirect('istore:homepage')
      else:
      
        order.products.add(order_item)
        messages.info(request,"item successfully added to cart")
        return redirect('istore:homepage')
    else:
      random=randint(1000,70000)
      order=Order.objects.create(customer=customer,user=user,transaction_id=random,complete=False)
      order.products.add(order_item)
      messages.info(request,"Cart successfully created and item added")
      return redirect('istore:description',slug=slug)
  else:
    messages.info(request,"You must be logged in")
    return redirect('istore:homepage')
  
  #return render(request,'istore/cart.html')
  
@login_required
def remove_cart(request,slug):
  if request.user.is_authenticated:
    customer=request.user.profile
    product=get_object_or_404(Product, slug=slug)
    order_qs=Order.objects.filter(customer=customer,complete=False)
    if order_qs.exists():
      order=order_qs[0]
      if order.products.filter(product__slug=product.slug).exists():
        order_item=OrderItem.objects.filter(product=product,customer=customer,complete=False)[0]
        order.products.remove(order_item)
        order_item.delete()
        messages.info(request,"item removed from cart")
        return redirect('istore:summary')
      else:
        messages.info(request,"item not in cart")
        return redirect('istore:homepage')
    else:
      messages.info(request,"no active order")
      return redirect('istore:homepage')
  else:
    messages.info(request,"You must login first")
    return redirect('istore:homepage')
    
    
    
@login_required
def cart_view(request):
  user=request.user
  customer=request.user.profile
  try:
    order=Order.objects.get(customer=customer,user=user,complete=False)
    return render(request,'istore/cart.html',{'order':order})
  except ObjectDoesNotExist:
    messages.error(request,"No active Order")
    return redirect('/')

def remove_one_cart(request,slug):
  if request.user.is_authenticated:
    user=request.user
    customer=request.user.profile
    product=get_object_or_404(Product, slug=slug)
    order_item=OrderItem.objects.get(product=product,customer=customer,complete=False)
    order_qs=Order.objects.filter(customer=customer,complete=False)
    if order_qs.exists():
      order=order_qs[0]
      if order.products.filter(product__slug=product.slug).exists():
        
        if order_item.quantity > 1:
          order_item.quantity -=1
          order_item.save()
        else:
          order.products.remove(order_item)
          order_item.save()
        messages.info(request,"Quantity  successfully updated")
        return redirect('istore:summary')
      
  else:
    messages.info(request,"You must be logged in")
    return redirect('istore:homepage')


def add_one_cart(request,slug):
  if request.user.is_authenticated:
    user=request.user
    customer=request.user.profile
    product=get_object_or_404(Product, slug=slug)
    order_item, created=OrderItem.objects.get_or_create(customer=customer,product=product,complete=False)
    order_qs=Order.objects.filter(customer=customer,user=user,complete=False)
    if order_qs.exists():
      order=order_qs[0]
      if order.products.filter(product__slug=product.slug).exists():
        
        order_item.quantity += 1
        order_item.save()
        messages.info(request,"Quantity successfully updated")
        return redirect('istore:summary')
    
    
def checkout_view(request):
  context ={}
  submitbutton = request.POST.get("btn-s")
  paystack_public = "pk_test_ef1bea703713ac519754d7b88f3b56ea141c1d67"
  try:
    order=Order.objects.get(customer=request.user.profile,complete=False)
  except ObjectDoesNotExist:
    return redirect("/")

  if request.method == 'POST':
    customer=request.user.profile
    address = request.POST['address']
    city = request.POST['city']
    phone_number = request.POST['phone_number']
    zip = request.POST['zip']
    country = request.POST['country']
    try:
      order=Order.objects.get(customer=customer,complete=False)  
      ship_address=ShippingAddress(customer=customer,
      city=city,
      address=address,
      phone_number=phone_number, zip=zip, country = country)
      ship_address.save()
      paystack_secret = "sk_test_b1630e59eb70f2592023210935c7894455b9ac1b"
      order.address=ship_address
      order.save()
      messages.success(request,"Success")
    except ObjectDoesNotExist:
      messages.error(request,"No active Order")
      return redirect('/')
  context={
    'order':order,
    'submitbutton':submitbutton,
    'paystack_public':paystack_public,
    'order':order
    }
  return render(request,'istore/checkout.html',context)
    
def shipping_address(request):
  return redirect('istore:checkout_view')
  

def verify_payment(request:HttpRequest, ref) -> HttpResponse:
    order = get_object_or_404(Order, transaction_id=ref)
    verified = order.verify_payment()
    if verified:
        messages.success(request," Alright mate you have successfullly purchased our package")
    else:
        messages.error(request,"verification failed ")
    return redirect('istore:checkout')

iBuy/istore/templates/istore/cart.html
{% extends 'layout.html' %}
{% load static %}


{% block content %}



<div class="page-wrapper">
  <div class="cart shopping">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
          <div class="block">
            <div class="product-list">
              <form method="post">
                <table class="table">
                  <thead>
                    <tr>
                      <th class="">Item Name</th>
					  <th class=""> Item Quantity
					  </th>
                      <th class="">Item Price</th>
                      <th class="">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
					{% for order_item in order.products.all %}
                    <tr class="">
                      <td class="">
                        <div class="product-info">
                          <img width="80" src="{{order_item.product.thumb.url}}" alt="" />
                          <a href="#!">{{order_item.product.name}}</a>
                        </div>
                      </td>
						
					  <td class="">
						<a class="cart-link"href="{% url 'istore:remove_one_cart' slug=order_item.product.slug  %}">
							<i class="tf-ion-minus"></i>
							</a>

						X{{order_item.quantity}}

						<a class="cart-link"href="{% url 'istore:one_cart' slug=order_item.product.slug %}">
							<i class="tf-ion-plus"></i>
						  </a>
					  </td>
                      <td class="">${{order_item.get_item_price}}</td>
                      <td class="">
                        <a class="product-remove" href="{% url 'istore:remove_cart' slug=order_item.product.slug %}">Remove</a>
                      </td>
                    </tr>

					
					{% endfor %}

					<tr>
						<td>Total price</td>
						
						<td colspan="5" rowspan="5">${{order.get_cart_total}}</td>
						
					  </tr>
                  
                  </tbody>
                </table>
                <a href="{% url 'istore:checkout' %}" class="btn btn-main pull-right float-right ">Checkout</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

iBuy/istore/templates/istore/cartd.html
{% extends 'layout.html' %}


{% block content %}

<style>

section{

    padding:60px 0;
    position:absolute;
    left:50%;
    top:50%;
    transform:translate(-50%,-50%);
    width:100%;
  }
  
.cart-shop , .cart-check{
  padding:10px 10px 10px 10px;
  color:#ffffff;
  border:10px solid transparent;
}


.cart-shop{
  background:#f4ec49;
}
  
.cart-check{
  background:#7cb342;
}

.table{
  width:100%;
}
</style>

<section>
<div class="container cart">
  <div class="row ">
    <div class="col-md-12">
      <div class="table-responsive text-nowrap table-md table-hover table-stripped cart-table  ">
        <table class="table table-stripped ">
          <thead>
            <tr>
            <th>#</th>
          <th>Item</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Total</th>
          </tr>
          </thead>
          <tbody>
    {% for order_item in order.products.all %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
          <td>{{order_item.product.name}}</td>
          
          
            <td>
             <a class="cart-link"href="{% url 'istore:remove_one_cart' slug=order_item.product.slug  %}">
            <i class="fa fa-minus"></i>
            </a>
            {{order_item.quantity}}
            <a class="cart-link"href="{% url 'istore:cart' slug=order_item.product.slug %}">
              <i class="fa fa-plus"></i>
            </a>
            
            </td>
          
          
            <td>${{order_item.product.price}}</td>
          
            <td>${{order_item.get_item_price}}</td>
            
            
            <td><a class="btn btn-outline-white btn-danger pull-right" href="{% url 'istore:remove_cart' slug=order_item.product.slug %}"><i class="fa fa-trash "></i></a>
            </td>
          </tr>
          
          {% endfor %}
          
          <tr>
            <td>Total price</td>
            
            <td colspan="5">${{order.get_cart_total}}</td>
            
          </tr>
          
          <tr>
            
            
            <td colspan="5">
              <a class="btn cart-shop btn-outline-white pull-right" href="{%  url 'istore:homepage' %}">
                Continue shopping
              </a>
            </td>
            {% if order.get_cart_total %}
            <td colspan="5">
              <a class="btn cart-check btn-outline-white  pull-right" name="checkout-btn" href="{% url 'istore:checkout' %}">Proceed To Checkout</a>
            </td>
            {% endif %}
          </tr>
          
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</section>







{% endblock %}

iBuy/istore/templates/istore/checkout.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
  <section class="page-header">
   <div class="container">
    <div class="row">
     <div class="col-md-12">
      <div class="content">
       <h1 class="page-name">
        Checkout
       </h1>
       <ol class="breadcrumb">
        <li>
         <a href="index.html">
          Home
         </a>
        </li>
        <li class="active">
         checkout
        </li>
       </ol>
      </div>
     </div>
    </div>
   </div>
  </section>
  <div class="page-wrapper">
   <div class="checkout shopping">
    <div class="container">
     <div class="row">
      <div class="col-md-8">
       <div class="block billing-details">
        <h4 class="widget-title">
         Billing Details
        </h4>
        {% if submitbutton != "submit" %}
        <form class="checkout-form" action="{% url 'istore:checkout' %}" method="post">
          {% csrf_token %}
         <div class="form-group">
          <label for="full_name">
           Full Name
          </label>
          <input class="form-control" id="full_name" name=""  placeholder="" type="text"/>
         </div>
         <div class="form-group">
          <label for="user_address">
           Address
          </label>
          <input class="form-control" id="user_address" name="address" required placeholder="" type="text"/>
         </div>
         <div class="form-group">
          <label for="user_address">
            Phone No
          </label>
          <input class="form-control" id="phone_number" name="phone_number" required placeholder="" type="text"/>
         </div>
         <div class="checkout-country-code clearfix">
          <div class="form-group">
           <label for="user_post_code">
            Zip Code
           </label>
           <input class="form-control" id="user_post_code" name="zip" type="text" value=""/>
          </div>
          <div class="form-group">
           <label for="user_city">
            City
           </label>
           <input class="form-control" id="user_city" name="city" type="text" value=""/>
          </div>
         </div>
         <div class="form-group">
          <label for="user_country">
           Country
          </label>
          <input class="form-control" id="user_country"  name="country" required placeholder="" type="text"/>
         </div>
         <button class="btn-main btn" type="submit" value="submit" name="btn-s">Submit</button>
        </form>
        {% endif %}
       </div>
       {% if submitbutton == "submit" %}
       <div class="block">
        <h4 class="widget-title">
         Payment Method
        </h4>
        <p>
         Credit Cart Details (Secure payment)
        </p>
        <div class="checkout-product-details">
         <div class="payment">
          <div class="card-details">
            <form >
              <script src="https://js.paystack.co/v1/inline.js"></script>
              <button type="button" class="btn btn-md btn-success btn-outline-white p-3" onclick="payWithPaystack()"> Pay With Paystack </button> 
            </form>
             
            <script>
              function payWithPaystack(){
                var handler = PaystackPop.setup({
                  key: '{{paystack_public}}',
                  email: '{{request.user.email}}',
                  amount: {{order.get_cart_total}} * 100,
                  currency: "NGN",
                  ref: '{{order.transaction_id}}',
                  firstname: '{{request.user.first_name}}',
                  lastname: '{{request.user.last_name}}',
                  // label: "Optional string that replaces customer email"
                  metadata: {
                     custom_fields: [
                        {
                            display_name: "Mobile Number",
                            variable_name: "mobile_number",
                            value: "+2348012345678"
                        }
                     ]
                  },
                  callback: function(response){
                      alert('success. transaction ref is ' + response.reference);

                      window.location.href= "{% url 'istore:verify_payment' order.transaction_id %}"
                  },

            

                  onClose: function(){
                      alert('window closed');
                  }
                });
                handler.openIframe();
              }
            </script>
          </div>
         </div>
        </div>
       </div>

       {% endif %}
      </div>
      <div class="col-md-4">
       <div class="product-checkout-details">
        <div class="block">
         <h4 class="widget-title">
          Order Summary
         </h4>
         {% for order_item in order.products.all %}
         <div class="media product-card">
          <a class="pull-left" href="{% url 'istore:description' order_item.product.slug %}">
           <img alt="Image" class="media-object" src="{{order_item.product.thumb.url}}"/>
          </a>
          <div class="media-body">
           <h4 class="media-heading">
            <a href="{% url 'istore:description' order_item.product.slug %}">
             {{ order_item.product.name }}
            </a>
           </h4>
           <p class="price">
            {{order_item.quantity}} x ${{order_item.product.price}}
           </p>
           <span class="remove">
            <a href="{% url 'istore:remove_cart' order_item.product.slug %}">Remove</a>
           </span>
          </div>
         </div>
         {% endfor %}
         <div class="discount-code">
          <p>
           Have a discount ?
           <a data-target="#coupon-modal" data-toggle="modal" href="#!">
            enter it here
           </a>
          </p>
         </div>
         <ul class="summary-prices">
          <li>
           <span>
            Subtotal:
           </span>
           <span class="price">
            ${{order.get_cart_total}}
           </span>
          </li>
          <li>
           <span>
            Shipping:
           </span>
           <span>
            Free
           </span>
          </li>
         </ul>
         <div class="summary-total">
          <span>
           Total
          </span>
          <span>
           ${{order.get_cart_total}}
          </span>
         </div>
         <div class="verified-icon">
          <img src="{% static 'images/shop/verified.png' %}"/>
         </div>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="coupon-modal" role="dialog" tabindex="-1">
   <div class="modal-dialog" role="document">
    <div class="modal-content">
     <div class="modal-body">
      <form>
       <div class="form-group">
        <input class="form-control" required placeholder="Enter Coupon Code" type="text"/>
       </div>
       <button class="btn btn-main" type="submit">
        Apply Coupon
       </button>
      </form>
     </div>
    </div>
   </div>
  </div>
{% endblock %}

iBuy/istore/templates/istore/checkoutd.html
{% extends 'layout.html' %}

{% block content %}
<style>
  
  .address-btn,.stack-btn{
    width:100%;
    border-radius:8px;
  }
  .stack-btn{
    background:green;
    margin-top: 5px;
  }
  form{
    width:100%;
  }
</style>



     <div class="container mt-5">
       <div class="row justify-content-center">
         <form method="post" action="{% url 'istore:checkout' %}">
           {%csrf_token%}
           <div class="col-md-12">
             {{form}}
           </div>
           
           <input type="submit" class="address-btn btn-primary mt-4 btn-outline-white" name="submit" value="submit">
           </div>
         </form>
         
         
        
           
           {% if form.is_valid %}
           
  <form>
    {% csrf_token %}
    <div class="row justify-content-center">
  <script src="https://js.paystack.co/v1/inline.js"></script>
  <a type="button" class="btn btn-outline-white stack-btn btn-rounded" value="Pay With Paystack" onlick="payWithPaystack()">payWithPaystack</a>
  </div>
</form>

<script>

          function payWithPaystack(){
            var handler = PaystackPop.setup({
              key: '{{paystack_public}}',
              email: '{{email}}',
              amount: {{order.get_cart_total}} * 100,
              currency: "NGN",
              ref: '{{order.transaction_id}}',
              firstname: 'Iyanu',
              lastname: 'Akinwumi',
              // label: "Optional string that replaces customer email"
              metadata: {
                  custom_fields: [
                    {
                        display_name: "Mobile Number",
                        variable_name: "mobile_number",
                        value: "+2348012345678"
                    }
                  ]
              },
              callback: function(response){
                  alert('success. transaction ref is ' + response.reference);

                  window.location.href= "{% url 'istore:verify_payment' order.transaction_id %}"
              },

        

              onClose: function(){
                  alert('window closed');
              }
            });
            handler.openIframe();
          }

             
         
</script>
{% endif %}
     </div>
     </div>
           
           
     
{% endblock %}

iBuy/istore/templates/istore/desc.html
{% extends 'layout.html' %}

{% block content %}

<style>
  .cart-btn{
    padding:10px;
    background:transparent;
    border-radius:6px;
    border:2px solid #111111;
    color:#111;
    
    
  }
  
  .desc{
    padding: 60px 0;
  }
  
  .desc span,h6{
    font-size:26px;
    color:#111;
    font-weight:700;
  }
</style>


<section class="desc">
  <div class="container">
    <div class="row mt-5 pt-4 justify-content-center">
      
      <div class="col-md-7">
        <img src="{{product.thumb.url}}"width="100%">
      </div>
      <div class="col-md-5 pt-2">
        <span class="badge bg-primary">{{product.category}}</span>
        <br>
        <span>{{product.name}}</span>
        <br>
        <span>${{product.price}}</span>
        <br>
        <a class="btn btn-outline-white cart-btn" href="{% url 'istore:cart' slug=product.slug %}">Add to Cart</a>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-12">
        <h6>Description</h6>
        {{product.description}}
      </div>
    </div>
  </div>
  
</section>

{% endblock %}

iBuy/istore/templates/istore/homepage.html
{% extends 'layout.html' %}

{% block content %}

<style>
.all{
  padding:60px 0;
  
}
.all  .container .content{

}



.jumbotron{
  background:#ffffff;
  margin:6px;
  border-radius:3px;
  height:95%;

}

.item-box img{
  height:200px;
  width: 100%;
}


.item-box h3, .item-box span{
  color:#111;
  text-decoration:none;
  font-size:26px;
  

}
</style>
<section class="all">
  <div class="container">
    <div class="row">
      {% for product in product %}
      <div class="col-md-4 text-center mt-5">
        <div class=" jumbotron">
        <a href="{% url 'istore:description' slug=product.slug %}">
          <img src="{{product.thumb.url}}" width="100%">
        
        <h3 class="mt-3">{{product.name}}</h3>
        <span>${{product.price}}</span>

        
        </a>
      </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}